controllerManager:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: quay.io/itsoiref/dpf-system
      tag: v0.1.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
imagePullSecrets: []

openvSwitchRunDir: /var/run/openvswitch
openvSwitchBinDir: /usr/bin
openvSwitchSharedLibraryDir: /lib
openvSwitchSharedLibrary64Dir: /lib64
