apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dpf-operator-system
resources:
- daemonset.yaml
- configmap.yaml
images:
- name: controller
  newName: quay.io/itsoiref/dpu-cni-provisioner
  newTag: v0.1.0
