imagePullSecrets: []
ovsHelper:
  image:
    repository: quay.io/itsoiref/dpf-system
    tag: v0.1.0

openvSwitchRunDir: /var/run/openvswitch
openvSwitchBinDir: /usr/bin
openvSwitchSharedLibraryDir: /lib