## Images built as part of the DPF release.
dmsImage: quay.io/itsoiref/hostdriver:v0.1.0
hostNetworkSetupImage: quay.io/itsoiref/hostdriver:v0.1.0
dpfSystemImage: quay.io/itsoiref/dpf-system:v0.1.0
dpfToolsImage: quay.io/itsoiref/dpf-tools:v0.1.0
ovsCniImage: quay.io/itsoiref/ovs-cni-plugin:v0.1.0
customOVNKubernetesImage: quay.io/itsoiref/ovn-kubernetes:v0.1.0

## Helm charts built as part of the DPF release.
dpuNetworkingHelmChart: oci://quay.io/itsoiref/dpu-networking:v0.1.0

## External images that are used inside helm charts deployed by the DPF Operator
multusImage: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.3
sriovDPImage: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.6.2
nvipamImage: ghcr.io/mellanox/nvidia-k8s-ipam:v0.3.5